### ISSUE TITLE
Not compatible with Angular 14

### ISSUE THREAD

**Issue by jesuscano80** [selemxmn/ngx-print#152]
**Describe the bug**
I have updated to Angular 14 and ngx-print is not compatible for.

**To Reproduce**
When use directive ngxPrint appears fail  Error: Module not found: Error: Can't resolve 'ngx-print/ngx-print'

**Ngx-Print Version**
 "ngx-print": "^1.2.1",

Angular CLI: 14.2.10
Node: 14.15.5
Package Manager: npm 6.14.11

**Comment by Core121** [comment]
That sounds like an issue with either the pathing to the package or the package not being installed.
I would first make sure the path is valid by deleting references to the NgxPrintModule in the app.module.ts. Then type NgxPrintModule in the imports section of app.module.ts. VS Code should auto create the import at the top of the file.
You may also need to import the package into the corresponding module that the error message is occurring on.

If that doesn't work, try deleting your node_modules folder and running 'npm i' in the terminal.
Ngx-print is compatible with Angular 14 since it runs on ViewEngine and Angular 14 still supports VewEngine libraries.

**Comment by newlabel123** [comment]
I am also currently having that issue but my angular version is 13.

Even after making IntelliJ pick the directory, it changes it to 
import {NgxPrintModule} from "ngx-print/src/lib/ngx-print.module";
instead of
import {NgxPrintModule} from "ngx-print";

And end up with another error which is 
core.mjs:6494 ERROR Error: Uncaught (in promise): TypeError: Cannot read properties of undefined (reading 'ɵmod')
TypeError: Cannot read properties of undefined (reading 'ɵmod')
    at getNgModuleDef (core.mjs:1137:1)
    at recurse (core.mjs:21813:1)
    at recurse (core.mjs:21824:1)
    at registerNgModuleType (core.mjs:21809:1)
    at new NgModuleFactory (core.mjs:21931:1)
    at Compiler.compileModuleSync (core.mjs:25189:1)
    at Compiler.compileModuleAsync (core.mjs:25195:1)
    at MergeMapSubscriber.project (router.mjs:3985:43)
    at MergeMapSubscriber._tryNext (mergeMap.js:44:1)
    at MergeMapSubscriber._next (mergeMap.js:34:1)
    at resolvePromise (zone.js:1262:1)
    at resolvePromise (zone.js:1216:1)
    at zone.js:1329:1
    at push.23484._ZoneDelegate.invokeTask (zone.js:443:1)
    at Object.onInvokeTask (core.mjs:25595:1)
    at push.23484._ZoneDelegate.invokeTask (zone.js:442:1)
    at push.23484.Zone.runTask (zone.js:214:1)
    at drainMicroTaskQueue (zone.js:632:1)

But when I remove NgxPrintModule from the module everything works perfectly fine.

**Comment by Core121** [comment]
Make sure you're using v1.2.1 if you're on angular 13. Though the error you described made me realize the build on npm was improper and needed swapping out. I've fixed the build and deprecated v1.3.0 in favor of the valid build in v1.3.1. This new build will only work on angular 15+ so please use v1.2.1 for anything earlier.
